{
  "Id": "1289931",
  "IdGerrit": "182327",
  "Files": "cinder/volume/api.py,cinder/volume/utils.py",
  "CommitParent": "daa751a62e46befed0982c6ce16b26f080040c38",
  "CommitPrevious": "0b2e7cbe\n68228eb7",
  "Responsible": "Neither",
  "Comments": "0b2e7cbe is not responsible\n68228eb7 is not responsible\nThe bug was caused by a migration "
}